const {chromium} = require('playwright');
const {spawn} = require('node:child_process');
const {once} = require('node:events');
const assert = require('node:assert/strict');
const path = require('node:path');

(async()=>{
  const fixture=spawn('python3',[path.join(__dirname,'serve_ui.py')],{stdio:['ignore','pipe','inherit']});
  let browser;
  try {
    // A failed fixture must fail CI, even if its stdout never emitted data.
    const [data]=await Promise.race([
      once(fixture.stdout,'data'),
      once(fixture,'exit').then(([code,signal])=>{throw new Error(`UI fixture exited before startup (${code ?? signal})`);}),
    ]);
    const url=data.toString().trim();
    const executablePath=process.env.CHROMIUM_EXECUTABLE_PATH || process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE;
    browser=await chromium.launch({headless:true,...(executablePath?{executablePath}:{})});
    const page=await browser.newPage({viewport:{width:1440,height:1100}});
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    const mutations=[];page.on('request',request=>{if(request.method()==='POST')mutations.push({path:new URL(request.url()).pathname,body:request.postDataJSON()});});
    const profileRemove=name=>page.locator(`[data-remove-profile="${name}"]`);
    await page.goto(url);
    await page.locator('#nodes').getByText('test-gateway',{exact:true}).waitFor();
    assert.equal(await page.locator('#host-count').textContent(),'1');
    assert.equal(await page.locator('#drift-count').textContent(),'1');
    await page.locator('#scan').click();
    await page.getByText('Suchlauf gestartet. Die Übersicht aktualisiert sich automatisch.').waitFor();
    await page.locator('#template').setInputFiles({name:'site.toml',mimeType:'text/plain',buffer:Buffer.from('[net_info]\nmcc=901\nmnc=1510\n[cell_info]\nlocation_area=1\ncolour_code=1\n[phy_io]\nbackend="SoapySdr"\n')});
    await page.getByText('Standort-Template gespeichert.').waitFor();
    await page.locator('#profile-form [name=name]').fill('TBS-02');
    await page.locator('#profile-form [name=issi]').fill('4010002');
    await page.locator('#profile-form button').click();
    await page.locator('#profile-list').getByText('TBS-02 · Bootstrap ↓').waitFor();
    assert.equal(await page.locator('#image-form [name=ref]').count(),0);
    assert.equal(await page.locator('#image-ref').count(),0);
    assert.match(await page.locator('.image-version-note').textContent(),/main.*automatisch/);
    assert.equal(await page.locator('#deploy-ref').inputValue(),'fixture-deployment-ref');
    assert.equal(await page.locator('#settings-ref').inputValue(),'fixture-deployment-ref');
    await page.locator('#target-service').selectOption('node-gateway');
    await page.locator('#deploy-form button[type=submit]').click();
    await page.locator('#plan').waitFor({state:'visible'});
    assert.match(await page.locator('#plan-text').textContent(),/test-gateway/);
    await page.locator('#execute').click();
    await page.locator('#job-list').getByText('Erfolgreich',{exact:true}).waitFor({timeout:15000});
    assert.match(await page.locator('#log').textContent(),/simulated installer/);
    assert.equal(await page.locator('#image-controller').inputValue(),'http://10.0.1.50:8320');
    await page.locator('#image-form [name=password]').fill('fixture-only-password');
    await page.locator('#image-build').click();
    await page.locator('#image-artifacts').getByText('Download bereit',{exact:true}).waitFor({timeout:15000});
    assert.match(await page.locator('#image-log').textContent(),/simulated image builder/);
    assert.match(await page.locator('#image-job-list').textContent(),/bbbbbbbb/);
    assert.match(await page.locator('#image-artifacts').textContent(),/bbbbbbbb/);
    const imageSubmission=mutations.find(request=>request.path==='/api/v1/images/build');
    assert.equal(imageSubmission.body.profile,'TBS-02');
    assert.equal(Object.hasOwn(imageSubmission.body,'ref'),false,'Pi image UI must not submit a branch, tag or commit');
    assert.equal(await page.locator('#image-form [name=password]').inputValue(),'');
    const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#image-artifacts').getByText('Image ↓',{exact:true}).click()]);
    assert.equal(download.suggestedFilename(),'fixture.img.xz');
    const readable=await download.createReadStream();const chunks=[];for await(const chunk of readable)chunks.push(chunk);
    assert.equal(Buffer.concat(chunks).toString(),'fixture image transport only');
    // Cancellation, busy/error handling, pending protection and actual successful
    // removal all use the saved-profile UI; successful requests reach the real API.
    await page.locator('#profile-form [name=name]').fill('TBS-03');
    await page.locator('#profile-form [name=issi]').fill('4010003');
    await page.locator('#profile-form button').click();
    await page.locator('#profile-list').getByText('TBS-03 · Bootstrap ↓').waitFor();
    await page.locator('#target-profile').selectOption('TBS-03');
    assert.equal(await page.locator('#image-profile').inputValue(),'TBS-03');
    const removeCount=()=>mutations.filter(request=>request.path==='/api/v1/profiles/remove').length;
    let confirmation='';
    page.once('dialog',async dialog=>{confirmation=dialog.message();await dialog.dismiss();});
    await profileRemove('TBS-03').click();
    assert.match(confirmation,/gespeicherte TBS-Profil „TBS-03“/);
    assert.match(confirmation,/installierte Basisstationen, Images und Buildprotokolle bleiben erhalten/);
    assert.equal(removeCount(),0,'Cancelled confirmation must not send a deletion request');
    assert.equal(await page.locator('.saved-profile').count(),2);
    const conflict='TBS-Profil wird von einem laufenden Auftrag verwendet.';
    await page.route('**/api/v1/profiles/remove',route=>route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({error:conflict})}));
    page.once('dialog',dialog=>dialog.accept());
    await profileRemove('TBS-03').click();
    await page.getByText(conflict,{exact:true}).waitFor();
    assert.equal(await page.locator('#notice.error').isVisible(),true);
    assert.equal(await page.locator('.saved-profile').count(),2,'Failed deletion must retain the profile list');
    assert.equal(await page.locator('#target-profile').inputValue(),'TBS-03');
    assert.equal(await page.locator('#image-profile').inputValue(),'TBS-03');
    assert.equal(await profileRemove('TBS-03').isEnabled(),true,'Failed request must restore the delete button');
    await page.unroute('**/api/v1/profiles/remove');
    let releaseRemoval;
    const pendingRemoval=new Promise(resolve=>{releaseRemoval=resolve;});
    let removalArrived;
    const awaitingRemoval=new Promise(resolve=>{removalArrived=resolve;});
    await page.route('**/api/v1/profiles/remove',async route=>{removalArrived();await pendingRemoval;await route.continue();});
    page.once('dialog',dialog=>dialog.accept());
    await profileRemove('TBS-03').click();
    await page.getByText('Wird gelöscht …',{exact:true}).waitFor();
    await awaitingRemoval;
    assert.equal(await page.locator('[data-remove-profile]:disabled').count(),2);
    const pendingCount=removeCount();
    const refreshMutationCount=mutations.length;
    await page.evaluate(()=>refresh());
    assert.equal(mutations.length,refreshMutationCount,'Refreshing the UI must not create mutation or Git-check requests');
    await page.locator('[data-remove-profile="TBS-03"]').dispatchEvent('click');
    assert.equal(removeCount(),pendingCount,'Repeated pending click must not submit twice');
    assert.equal(await page.locator('[data-remove-profile]:disabled').count(),2,'Polling must retain pending-button protection');
    releaseRemoval();
    await page.getByText('TBS-Profil „TBS-03“ gelöscht.',{exact:true}).waitFor();
    await page.unroute('**/api/v1/profiles/remove');
    assert.equal(await page.locator('.saved-profile').count(),1);
    assert.equal(await page.locator('#image-profile').inputValue(),'','Deleting the selected profile must not silently select another image profile');
    assert.equal(await page.locator('#target-profile').inputValue(),'');
    assert.equal(await page.locator('#image-hostname').inputValue(),'');
    assert.equal(await page.locator('#image-build').isDisabled(),true);
    await page.waitForFunction(()=>!document.querySelector('[data-remove-profile="TBS-02"]').disabled);
    assert.equal(await page.locator('#image-artifacts .image-card').count(),1,'Profile removal must preserve existing images');
    assert.match(await page.locator('#job-list').textContent(),/Erfolgreich/);
    for(const [name,applied] of [['TBS-04',true],['TBS-05',null]]){
      await page.locator('#profile-form [name=name]').fill(name);
      await page.locator('#profile-form [name=issi]').fill(name==='TBS-04'?'4010004':'4010005');
      await page.locator('#profile-form button').click();
      await page.locator('#profile-list').getByText(`${name} · Bootstrap ↓`,{exact:true}).waitFor();
      await page.locator('#target-profile').selectOption(name);
      const before=removeCount();
      const persistenceWarning='Profiländerung wurde gespeichert, Persistenzbestätigung fehlgeschlagen.';
      await page.route('**/api/v1/profiles/remove',async route=>{
        // Commit the actual server-side removal before simulating a response whose
        // final directory-fsync failed. GET must therefore see the removed profile.
        const response=await route.fetch();
        assert.equal(response.status(),200);
        await route.fulfill({response,status:503,contentType:'application/json',body:JSON.stringify({error:persistenceWarning,profile_change_applied:applied,durability_uncertain:true})});
      });
      page.once('dialog',dialog=>dialog.accept());
      await profileRemove(name).click();
      await page.waitForFunction(()=>document.querySelector('#notice.error')?.textContent.includes('Persistenzbestätigung fehlgeschlagen'));
      await page.waitForFunction(()=>!document.querySelector('[data-remove-profile="TBS-02"]').disabled);
      await page.unroute('**/api/v1/profiles/remove');
      assert.equal(removeCount(),before+1,'Persistence uncertainty must not resubmit the deletion');
      assert.equal(await page.locator('.saved-profile').count(),1);
      assert.equal(await page.locator('#target-profile').inputValue(),'');
      assert.equal(await page.locator('#image-profile').inputValue(),'');
      assert.equal(await page.locator('#image-hostname').inputValue(),'');
      assert.equal(await page.locator('#image-build').isDisabled(),true);
      const current=await (await page.request.get(url+'/api/v1/profiles')).json();
      assert.deepEqual(current.map(profile=>profile.name),['TBS-02'],'UI must reconcile with the actual persisted profile state after a 503');
      if(applied===true)assert.match(await page.locator('#notice').textContent(),/gelöscht, aber die dauerhafte Speicherung konnte nicht bestätigt werden/);
      assert.equal(await page.locator('#image-artifacts .image-card').count(),1);
    }
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.screenshot({path:'/tmp/netcore-deployment-desktop.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:'/tmp/netcore-deployment-mobile.png',fullPage:true});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    assert.deepEqual(errors,[]);
    await page.locator('#target-profile').selectOption('TBS-02');
    await page.locator('#image-profile').selectOption('TBS-02');
    page.once('dialog',dialog=>dialog.accept());
    await profileRemove('TBS-02').click();
    await page.getByText('TBS-Profil „TBS-02“ gelöscht.',{exact:true}).waitFor();
    await page.getByText('Noch keine TBS-Profile gespeichert.',{exact:true}).waitFor();
    assert.equal(await page.locator('#profile-list a').getAttribute('href'),'#profile-form');
    assert.equal(await page.locator('#target-profile').inputValue(),'');
    assert.equal(await page.locator('#image-profile').inputValue(),'');
    assert.equal(await page.locator('#image-profile option').count(),1);
    assert.equal(await page.locator('#image-build').isDisabled(),true);
    assert.equal(await page.locator('#image-artifacts .image-card').count(),1,'Removing the last profile must not remove previously built images');
    await page.screenshot({path:'/tmp/netcore-deployment-empty-profiles-mobile.png',fullPage:true});
    page.once('dialog',dialog=>dialog.accept());
    await page.locator('#image-artifacts').getByText('Löschen',{exact:true}).click();
    await page.getByText('Image gelöscht. Das Buildprotokoll bleibt erhalten.').waitFor();
    assert.equal(await page.locator('#image-artifacts .image-card').count(),0);
    assert.deepEqual(errors,[]);
    console.log('PASS: real WebUI, discovery, TBS wizard, remote job, automatic-main image submission/download, profile cancel/error/pending/deletion/503 reconciliation/empty state, preserved images, desktop and mobile');
  } finally {if(browser)await browser.close();fixture.kill('SIGTERM');}
})().catch(e=>{console.error(e);process.exitCode=1;});
