// NETCORE-KOMMENTAR – Was: Enthält einen Teil der Logik für die Verbindung zwischen Basisstationen und Backend-Diensten.
// NETCORE-KOMMENTAR – Warum: Die Trennung in eine eigene Datei macht Zuständigkeit, Wartung und Fehlersuche übersichtlicher.

// Was: Legt den festen Wert `INDEX_HTML` für index html fest.
// Warum: Der benannte Wert vermeidet schwer verständliche Zahlen oder Texte direkt in der Programmlogik und hält Änderungen zentral.
pub const INDEX_HTML: &str = r#"<!doctype html>
<html lang="de">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>NetCore Node Gateway</title>
<style>
:root{color-scheme:dark;--bg:#0b1118;--panel:#121c27;--panel2:#182635;--line:#294056;--text:#eaf2fa;--muted:#91a6ba;--good:#55d68b;--warn:#ffbf5b;--bad:#ff6b73;--accent:#53a8ff}
*{box-sizing:border-box}body{margin:0;background:linear-gradient(145deg,#081019,#102033);color:var(--text);font:14px/1.45 system-ui,-apple-system,Segoe UI,sans-serif;min-height:100vh}header{display:flex;align-items:center;justify-content:space-between;padding:18px 24px;border-bottom:1px solid var(--line);background:rgba(8,15,23,.92);position:sticky;top:0;z-index:5}h1{font-size:19px;margin:0}h2{font-size:16px;margin:0 0 12px}main{padding:20px;max-width:1600px;margin:auto}.muted{color:var(--muted)}.cards{display:grid;grid-template-columns:repeat(6,minmax(130px,1fr));gap:12px;margin-bottom:16px}.card,.panel{background:rgba(18,28,39,.94);border:1px solid var(--line);border-radius:12px;box-shadow:0 10px 30px rgba(0,0,0,.18)}.card{padding:14px}.card b{font-size:24px;display:block;margin-top:4px}.grid{display:grid;grid-template-columns:minmax(620px,1.5fr) minmax(360px,1fr);gap:16px}.panel{padding:16px;min-width:0}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:9px 8px;border-bottom:1px solid #223547;vertical-align:top}th{color:var(--muted);font-weight:600;font-size:12px;text-transform:uppercase;letter-spacing:.04em}tr[data-id]{cursor:pointer}tr[data-id]:hover{background:#17283a}.badge{display:inline-flex;align-items:center;border-radius:999px;padding:3px 8px;font-size:12px;border:1px solid var(--line)}.connected{color:var(--good)}.disconnected{color:var(--muted)}.stale,.blocked{color:var(--bad)}.maintenance{color:var(--warn)}button,input{font:inherit}button{border:1px solid var(--line);background:#1b3044;color:var(--text);border-radius:8px;padding:8px 11px;cursor:pointer}button:hover{border-color:var(--accent)}button.danger{background:#4b2028;border-color:#7f3540}button.warn{background:#493a20;border-color:#7b6230}.toolbar{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.toolbar input{background:#0d1823;color:var(--text);border:1px solid var(--line);border-radius:8px;padding:8px 10px;min-width:250px}.detail{display:grid;grid-template-columns:140px 1fr;gap:7px 12px;word-break:break-word}.detail dt{color:var(--muted)}.detail dd{margin:0}.events{max-height:430px;overflow:auto}.event{padding:9px 0;border-bottom:1px solid #223547}.event small{color:var(--muted)}.severity-error,.severity-warning{color:var(--warn)}.severity-error{color:var(--bad)}#toast{position:fixed;right:20px;bottom:20px;background:#122538;border:1px solid var(--line);padding:12px 15px;border-radius:10px;display:none;max-width:420px}.wide{grid-column:1/-1}@media(max-width:1050px){.cards{grid-template-columns:repeat(3,1fr)}.grid{grid-template-columns:1fr}}@media(max-width:650px){header{padding:14px}main{padding:12px}.cards{grid-template-columns:repeat(2,1fr)}.panel{overflow:auto}.toolbar input{min-width:160px;max-width:100%}}
</style>
</head>
<body>
<header><div><h1>NetCore Node Gateway</h1><div class="muted" id="instance">wird geladen …</div></div><div class="toolbar"><span id="ready" class="badge">Status</span><button onclick="setToken()">API-Token</button><button onclick="refreshAll()">Aktualisieren</button></div></header>
<main>
<section class="cards">
<div class="card"><span class="muted">Verbunden</span><b id="connected">–</b></div>
<div class="card"><span class="muted">Bekannte Nodes</span><b id="total">–</b></div>
<div class="card"><span class="muted">Upstream</span><b id="upstream">–</b></div>
<div class="card"><span class="muted">Stale</span><b id="stale">–</b></div>
<div class="card"><span class="muted">Nachrichten</span><b id="messages">–</b></div>
<div class="card"><span class="muted">Uptime</span><b id="uptime">–</b></div>
</section>
<section class="grid">
<div class="panel"><div class="toolbar" style="justify-content:space-between"><h2>Basisstationen</h2><input id="filter" placeholder="Node, Standort oder Stationsname filtern" oninput="renderNodes()"></div><table><thead><tr><th>Status</th><th>Node</th><th>Standort</th><th>Zelle</th><th>Letzter Kontakt</th><th>Upstream</th></tr></thead><tbody id="nodes"></tbody></table></div>
<div class="panel"><h2>Node-Details</h2><div id="detail" class="muted">Eine Basisstation auswählen.</div><div id="actions" class="toolbar" style="margin-top:16px"></div></div>
<div class="panel wide"><h2>Gateway-Ereignisse</h2><div id="events" class="events"></div></div>
</section>
</main><div id="toast"></div>
<script>
let nodes=[],selected=null,lastEvent=0;
const tokenKey='netcore-node-gateway-token';
function token(){return sessionStorage.getItem(tokenKey)||''}
function setToken(){const value=prompt('Viewer-, Operator- oder Admin-Token:',token());if(value!==null){sessionStorage.setItem(tokenKey,value.trim());refreshAll()}}
async function api(path,opts={}){opts.headers=Object.assign({'Accept':'application/json'},opts.headers||{});if(token())opts.headers.Authorization='Bearer '+token();if(opts.body&&!opts.headers['Content-Type'])opts.headers['Content-Type']='application/json';const r=await fetch(path,opts);if(r.status===401){throw new Error('Nicht autorisiert – bitte API-Token setzen.')}const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error((data&&data.error)||data||('HTTP '+r.status));return data}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function age(ms){if(ms==null)return '–';const s=Math.floor(ms/1000);if(s<60)return s+' s';if(s<3600)return Math.floor(s/60)+' min';return Math.floor(s/3600)+' h'}
function fmtUptime(s){if(s<60)return s+' s';if(s<3600)return Math.floor(s/60)+' min';if(s<86400)return Math.floor(s/3600)+' h';return Math.floor(s/86400)+' d'}
function stateLabel(n){return `<span class="badge ${esc(n.connection_state)}">${esc(n.connection_state)}</span>`}
async function refreshOverview(){const o=await api('/api/v1/overview');document.getElementById('instance').textContent=o.instance_name+' · gestartet '+o.started_at;document.getElementById('connected').textContent=o.connected_nodes;document.getElementById('total').textContent=o.total_nodes;document.getElementById('upstream').textContent=o.upstream_connected_nodes;document.getElementById('stale').textContent=o.stale_nodes;document.getElementById('messages').textContent=o.total_node_messages;document.getElementById('uptime').textContent=fmtUptime(o.uptime_seconds);const r=document.getElementById('ready');r.textContent=o.ready?'bereit':'nicht bereit';r.className='badge '+(o.ready?'connected':'stale')}
async function refreshNodes(){nodes=await api('/api/v1/nodes');renderNodes();if(selected){const found=nodes.find(n=>n.node_id===selected);if(found)renderDetail(found);else{selected=null;renderDetail(null)}}}
function renderNodes(){const q=(document.getElementById('filter').value||'').toLowerCase();const rows=nodes.filter(n=>JSON.stringify(n).toLowerCase().includes(q)).map(n=>{const i=n.identity||{};return `<tr data-id="${esc(n.node_id)}" onclick="selectNode('${esc(n.node_id)}')"><td>${stateLabel(n)}</td><td><b>${esc(n.node_id)}</b><br><small class="muted">${esc(i.stack_version||'')}</small></td><td>${esc(i.station_name||'–')}<br><small class="muted">${esc(i.site||'')}</small></td><td>${i.mcc??'–'}/${i.mnc??'–'} · LA ${i.location_area??'–'}<br><small class="muted">C ${i.main_carrier??'–'} · CC ${i.colour_code??'–'}</small></td><td>${age(n.last_seen_age_ms)}</td><td class="${n.upstream_connected?'connected':'disconnected'}">${n.upstream_connected?'verbunden':'getrennt'}</td></tr>`}).join('');document.getElementById('nodes').innerHTML=rows||'<tr><td colspan="6" class="muted">Keine Nodes gefunden.</td></tr>'}
function selectNode(id){selected=id;renderDetail(nodes.find(n=>n.node_id===id))}
function renderDetail(n){const d=document.getElementById('detail'),a=document.getElementById('actions');if(!n){d.innerHTML='<span class="muted">Eine Basisstation auswählen.</span>';a.innerHTML='';return}const i=n.identity||{},c=n.capabilities||{};d.innerHTML=`<dl class="detail"><dt>Node-ID</dt><dd>${esc(n.node_id)}</dd><dt>Status</dt><dd>${stateLabel(n)}</dd><dt>Session</dt><dd>${esc(n.session_id||'–')}</dd><dt>Peer</dt><dd>${esc(n.peer||'–')}</dd><dt>Protokoll</dt><dd>${esc(n.protocol_version||'–')}</dd><dt>Station</dt><dd>${esc(i.station_name||'–')}</dd><dt>Standort</dt><dd>${esc(i.site||'–')}</dd><dt>Reconnects</dt><dd>${n.reconnect_count}</dd><dt>Telemetrie</dt><dd>${n.telemetry_messages}</dd><dt>Upstream</dt><dd>${n.upstream_connected?'verbunden':'getrennt'} ${esc(n.upstream_last_error||'')}</dd><dt>Fähigkeiten</dt><dd>${Object.entries(c).filter(x=>x[1]===true).map(x=>esc(x[0])).join(', ')||'–'}</dd><dt>Letzte Trennung</dt><dd>${esc(n.last_disconnect_reason||'–')}</dd></dl>`;a.innerHTML=`<button onclick="action('reconnect')">Reconnect</button><button onclick="action('disconnect')">Trennen</button><button class="warn" onclick="toggle('maintenance',${!n.maintenance})">Wartung ${n.maintenance?'beenden':'aktivieren'}</button><button class="danger" onclick="toggle('block',${!n.blocked})">${n.blocked?'Entsperren':'Sperren'}</button>`}
async function action(name){if(!selected)return;if(!confirm(`${name} für ${selected} ausführen?`))return;try{await api(`/api/v1/nodes/${encodeURIComponent(selected)}/${name}`,{method:'POST',body:'{}'});toast('Aktion ausgeführt');await refreshNodes()}catch(e){toast(e.message,true)}}
async function toggle(name,value){if(!selected)return;try{await api(`/api/v1/nodes/${encodeURIComponent(selected)}/${name}`,{method:'POST',body:JSON.stringify(name==='block'?{blocked:value}:{enabled:value})});toast('Einstellung gespeichert');await refreshNodes()}catch(e){toast(e.message,true)}}
async function refreshEvents(){const page=await api('/api/v1/events?after='+lastEvent+'&limit=100');if(page.truncated)document.getElementById('events').innerHTML='';if(page.events.length){lastEvent=page.next_after;const html=page.events.slice().reverse().map(e=>`<div class="event severity-${esc(e.severity)}"><b>${esc(e.summary)}</b> <span class="muted">${esc(e.node_id||'Gateway')}</span><br><small>${esc(e.timestamp)} · ${esc(e.category)}</small></div>`).join('');document.getElementById('events').insertAdjacentHTML('afterbegin',html);while(document.getElementById('events').children.length>200)document.getElementById('events').lastElementChild.remove()}}
function toast(msg,bad=false){const t=document.getElementById('toast');t.textContent=msg;t.style.display='block';t.style.borderColor=bad?'var(--bad)':'var(--line)';setTimeout(()=>t.style.display='none',4000)}
async function refreshAll(){try{await Promise.all([refreshOverview(),refreshNodes(),refreshEvents()])}catch(e){toast(e.message,true)}}
refreshAll();setInterval(refreshAll,3000);
</script>
</body></html>"#;
