#!/usr/bin/env python3
from __future__ import annotations

import argparse
import fcntl
import json
import os
import re
import signal
import subprocess
import sys
import time
import tomllib
from pathlib import Path
from typing import Any


def b(value: Any, default: bool = False) -> bool:
    if isinstance(value, bool):
        return value
    if value is None:
        return default
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


def sid(value: Any) -> str:
    text = re.sub(r"[^a-zA-Z0-9_.:-]+", "-", str(value or "").strip()).strip("-")
    return text or "netcore"


def q(value: Any) -> str:
    return str(value or "").replace("\\", "\\\\").replace('"', '\\"')


def load(path: Path) -> dict[str, Any]:
    with path.open("rb") as handle:
        return tomllib.load(handle)


def atomic_write(path: Path, content: str, mode: int | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    if mode is not None:
        os.chmod(tmp, mode)
    tmp.replace(path)


def atomic_json(path: Path, data: dict[str, Any]) -> None:
    atomic_write(path, json.dumps(data, indent=2, sort_keys=True) + "\n", 0o640)


def names(cfg: dict[str, Any]) -> dict[str, str]:
    node = sid(cfg["service"]["node_id"]).lower()
    return {
        "node": node,
        "native": sid(cfg["native_tbs"]["username"]),
        "central_ep": f"netcore-central-{node}",
        "central_auth": f"netcore-central-{node}-auth",
        "central_aor": f"netcore-central-{node}-aor",
        "central_reg": f"netcore-central-{node}-registration",
        "pbx_ep": f"netcore-pbx-fallback-{node}",
        "pbx_auth": f"netcore-pbx-fallback-{node}-auth",
        "pbx_aor": f"netcore-pbx-fallback-{node}-aor",
        "pbx_reg": f"netcore-pbx-fallback-{node}-registration",
    }


def ensure(cfg: dict[str, Any]) -> None:
    required = [
        ("service.node_id", cfg.get("service", {}).get("node_id")),
        ("native_tbs.username", cfg.get("native_tbs", {}).get("username")),
        ("central.host", cfg.get("central", {}).get("host")),
        ("central.username", cfg.get("central", {}).get("username")),
        ("fallback_pbx.host", cfg.get("fallback_pbx", {}).get("host")),
    ]
    missing = [name for name, value in required if not str(value or "").strip()]
    if missing:
        raise ValueError("missing required values: " + ", ".join(missing))
    mode = str(cfg.get("fallback_pbx", {}).get("mode", "registration")).lower()
    if mode != "registration":
        raise ValueError("Phase 11c requires fallback_pbx.mode = registration")
    if str(cfg.get("failover", {}).get("default_mode", "central")) not in {"central", "pbx_direct"}:
        raise ValueError("failover.default_mode must be central or pbx_direct")


def render_pjsip_base(cfg: dict[str, Any]) -> str:
    asterisk = cfg["asterisk"]
    native = cfg["native_tbs"]
    central = cfg["central"]
    pbx = cfg["fallback_pbx"]
    n = names(cfg)
    lines: list[str] = [
        "; Generated by NetCore-TETRA Phase 11c. Do not edit manually.",
        "; Registration objects live in separate mutually exclusive files.",
        "[netcore-tbs-transport]",
        "type=transport",
        "protocol=udp",
        f"bind={asterisk.get('sip_bind', '0.0.0.0:5060')}",
        "allow_reload=yes",
        "",
        f"[{n['native']}]",
        "type=endpoint",
        "context=netcore-from-native-tbs",
        "disallow=all",
        f"allow={native.get('allow', 'ulaw')}",
        f"auth={n['native']}",
        f"aors={n['native']}",
        "direct_media=no",
        "rtp_symmetric=yes",
        "force_rport=yes",
        "rewrite_contact=yes",
        "identify_by=auth_username,username",
        "",
        f"[{n['native']}]",
        "type=auth",
        "auth_type=userpass",
        f"username={n['native']}",
        f"password={native.get('password', '')}",
        "",
        f"[{n['native']}]",
        "type=aor",
        "max_contacts=1",
        "remove_existing=yes",
        "qualify_frequency=5",
        "qualify_timeout=2.0",
        "",
    ]
    if b(central.get("enabled", True), True):
        host = str(central["host"])
        port = int(central.get("port", 5060))
        lines += [
            f"[{n['central_auth']}]",
            "type=auth",
            "auth_type=userpass",
            f"username={central.get('username', '')}",
            f"password={central.get('password', '')}",
            "",
            f"[{n['central_aor']}]",
            "type=aor",
            f"contact=sip:{host}:{port}",
            f"qualify_frequency={int(central.get('qualify_frequency_secs', 5))}",
            f"qualify_timeout={float(central.get('qualify_timeout_secs', 2))}",
            "",
            f"[{n['central_ep']}]",
            "type=endpoint",
            "transport=netcore-tbs-transport",
            "context=netcore-from-central-switch",
            "disallow=all",
            f"allow={central.get('allow', 'ulaw')}",
            f"aors={n['central_aor']}",
            f"outbound_auth={n['central_auth']}",
            f"from_user={central.get('username', '')}",
            f"from_domain={host}",
            "direct_media=no",
            "rtp_symmetric=yes",
            "force_rport=yes",
            "rewrite_contact=yes",
            "",
            f"[netcore-central-identify-{n['node']}]",
            "type=identify",
            f"endpoint={n['central_ep']}",
            f"match={host}",
            "",
        ]
    if b(pbx.get("enabled", True), True):
        host = str(pbx["host"])
        port = int(pbx.get("port", 5060))
        auth_user = str(pbx.get("auth_username") or pbx.get("username") or pbx.get("from_user") or "").strip()
        password = str(pbx.get("password") or "")
        lines += [
            f"[{n['pbx_aor']}]",
            "type=aor",
            f"contact=sip:{host}:{port}",
            f"qualify_frequency={int(pbx.get('qualify_frequency_secs', 5))}",
            f"qualify_timeout={float(pbx.get('qualify_timeout_secs', 2))}",
            "",
        ]
        auth_line = ""
        if auth_user and password:
            lines += [
                f"[{n['pbx_auth']}]",
                "type=auth",
                "auth_type=userpass",
                f"username={auth_user}",
                f"password={password}",
                "",
            ]
            auth_line = f"outbound_auth={n['pbx_auth']}"
        lines += [
            f"[{n['pbx_ep']}]",
            "type=endpoint",
            "transport=netcore-tbs-transport",
            "context=netcore-from-pbx-fallback",
            "disallow=all",
            f"allow={pbx.get('allow', 'ulaw')}",
            f"aors={n['pbx_aor']}",
            *([auth_line] if auth_line else []),
            f"from_user={pbx.get('from_user') or pbx.get('username') or ''}",
            f"from_domain={pbx.get('from_domain') or host}",
            "direct_media=no",
            "rtp_symmetric=yes",
            "force_rport=yes",
            "rewrite_contact=yes",
            "",
        ]
        for idx, match in enumerate(pbx.get("match") or [host], 1):
            lines += [
                f"[netcore-pbx-fallback-identify-{n['node']}-{idx}]",
                "type=identify",
                f"endpoint={n['pbx_ep']}",
                f"match={match}",
                "",
            ]
    return "\n".join(lines).rstrip() + "\n"


def render_central_registration(cfg: dict[str, Any]) -> str:
    central = cfg["central"]
    n = names(cfg)
    host = str(central["host"])
    port = int(central.get("port", 5060))
    expiration = int(central.get("registration_expiration_secs", 30))
    return "\n".join([
        "; Phase 11c CENTRAL registration. Loaded only in central mode.",
        f"[{n['central_reg']}]",
        "type=registration",
        "transport=netcore-tbs-transport",
        f"outbound_auth={n['central_auth']}",
        f"server_uri=sip:{host}:{port}",
        f"client_uri=sip:{central.get('username', '')}@{host}",
        f"contact_user={central.get('username', '')}",
        "retry_interval=5",
        "forbidden_retry_interval=30",
        "fatal_retry_interval=30",
        "max_retries=0",
        f"expiration={expiration}",
        "line=yes",
        f"endpoint={n['central_ep']}",
        "",
    ])


def render_pbx_registration(cfg: dict[str, Any]) -> str:
    pbx = cfg["fallback_pbx"]
    n = names(cfg)
    host = str(pbx["host"])
    port = int(pbx.get("port", 5060))
    username = str(pbx.get("username") or pbx.get("auth_username") or pbx.get("from_user") or "").strip()
    if not username:
        raise ValueError("fallback_pbx.username or from_user is required for registration failover")
    auth_user = str(pbx.get("auth_username") or username).strip()
    password = str(pbx.get("password") or "")
    expiration = int(pbx.get("registration_expiration_secs", 30))
    lines = [
        "; Phase 11c PBX DIRECT registration. Loaded only in confirmed fallback mode.",
        f"[{n['pbx_reg']}]",
        "type=registration",
        "transport=netcore-tbs-transport",
    ]
    if auth_user and password:
        lines.append(f"outbound_auth={n['pbx_auth']}")
    lines += [
        f"server_uri=sip:{host}:{port}",
        f"client_uri=sip:{username}@{host}",
        f"contact_user={pbx.get('contact_user') or username}",
        "retry_interval=5",
        "forbidden_retry_interval=30",
        "fatal_retry_interval=30",
        "max_retries=0",
        f"expiration={expiration}",
        f"endpoint={n['pbx_ep']}",
        "",
    ]
    return "\n".join(lines)


def render_active_registration(cfg: dict[str, Any], mode: str) -> str:
    failover = cfg["failover"]
    if mode == "central":
        target = Path(failover["central_registration_file"]).name
    elif mode == "pbx_direct":
        target = Path(failover["pbx_registration_file"]).name
    else:
        raise ValueError(f"invalid registration mode: {mode}")
    return f"; Phase 11c mutually exclusive active registration: {mode}\n#include {target}\n"


def render_extensions(cfg: dict[str, Any]) -> str:
    asterisk = cfg["asterisk"]
    central = cfg["central"]
    pbx = cfg["fallback_pbx"]
    routing = cfg["routing"]
    n = names(cfg)
    cto = int(asterisk.get("central_dial_timeout_secs", 60))
    pto = int(asterisk.get("fallback_dial_timeout_secs", 60))
    tto = int(asterisk.get("tetra_dial_timeout_secs", 35))
    prefix = str(routing.get("fallback_tetra_prefix", ""))
    strip = b(routing.get("strip_fallback_tetra_prefix", False))
    lines = [
        "; Generated by NetCore-TETRA Phase 11c. Do not edit manually.",
        "[netcore-from-native-tbs]",
        "exten => _X!,1,NoOp(NetCore TBS -> Telefonie ${EXTEN}; central Vermittlung mit exklusivem PBX-Fallback)",
        " same => n,Set(__NETCORE_SIP_ROUTE=central)",
        f" same => n,Dial(PJSIP/${{EXTEN}}@{n['central_ep']},{cto})",
    ]
    if b(routing.get("fallback_on_chanunavail", True), True):
        lines += [" same => n,GotoIf($[\"${DIALSTATUS}\"=\"CHANUNAVAIL\"]?consider-fallback)"]
    if b(routing.get("fallback_on_congestion", True), True):
        lines += [" same => n,GotoIf($[\"${DIALSTATUS}\"=\"CONGESTION\"]?consider-fallback)"]
    lines += [
        " same => n,Goto(done)",
        " same => n(consider-fallback),GotoIf($[\"${DB(netcore/failover_mode)}\"=\"pbx_direct\"]?fallback:central-not-confirmed-down)",
        " same => n(central-not-confirmed-down),Set(DIALSTATUS=CHANUNAVAIL)",
        " same => n,Goto(done)",
        " same => n(fallback),Set(__NETCORE_SIP_ROUTE=direct-pbx-fallback)",
        f" same => n,Dial(PJSIP/${{EXTEN}}@{n['pbx_ep']},{pto})",
        " same => n(done),Hangup()",
        "",
        "[netcore-from-central-switch]",
        "exten => _X!,1,NoOp(NetCore central SIP Switch -> local TBS ${EXTEN})",
        f" same => n,Set(NETCORE_TBS_CONTACTS=${{PJSIP_DIAL_CONTACTS({n['native']},{n['native']},${{EXTEN}})}})",
        " same => n,GotoIf($[\"${NETCORE_TBS_CONTACTS}\"=\"\"]?unavailable)",
        f" same => n,Dial(${{NETCORE_TBS_CONTACTS}},{tto})",
        " same => n,Hangup()",
        " same => n(unavailable),Congestion(5)",
        "",
        "[netcore-from-pbx-fallback]",
        "exten => _X!,1,NoOp(NetCore direct PBX fallback -> local TBS ${EXTEN})",
        " same => n,GotoIf($[\"${DB(netcore/failover_mode)}\"=\"pbx_direct\"]?fallback-active:fallback-blocked)",
        " same => n(fallback-blocked),Hangup(21)",
        " same => n(fallback-active),NoOp(Confirmed PBX_DIRECT_ACTIVE)",
    ]
    if not b(routing.get("accept_direct_pbx_fallback", True), True):
        lines += [" same => n,Hangup(21)"]
    else:
        if prefix:
            lines += [
                f" same => n,GotoIf($[\"${{EXTEN:0:{len(prefix)}}}\"=\"{prefix}\"]?prefixok:badprefix)",
                " same => n(prefixok),NoOp(Fallback prefix accepted)",
            ]
            lines += [f" same => n,Set(NETCORE_TETRA_NUMBER=${{EXTEN:{len(prefix)}}})" if strip else " same => n,Set(NETCORE_TETRA_NUMBER=${EXTEN})"]
            lines += [" same => n,Goto(deliver)", " same => n(badprefix),Hangup(21)"]
        else:
            lines += [" same => n,Set(NETCORE_TETRA_NUMBER=${EXTEN})"]
        lines += [
            f" same => n(deliver),Set(NETCORE_TBS_CONTACTS=${{PJSIP_DIAL_CONTACTS({n['native']},{n['native']},${{NETCORE_TETRA_NUMBER}})}})",
            " same => n,GotoIf($[\"${NETCORE_TBS_CONTACTS}\"=\"\"]?unavailable)",
            f" same => n,Dial(${{NETCORE_TBS_CONTACTS}},{tto})",
            " same => n,Hangup()",
            " same => n(unavailable),Congestion(5)",
        ]
    return "\n".join(lines).rstrip() + "\n"


def render_rtp(cfg: dict[str, Any]) -> str:
    a = cfg["asterisk"]
    return "; Generated by NetCore-TETRA Phase 11c.\n[general]\n" + f"rtpstart={int(a.get('rtp_start', 30200))}\nrtpend={int(a.get('rtp_end', 30300))}\n"


def render_native_snippet(cfg: dict[str, Any]) -> str:
    native = cfg["native_tbs"]
    bind_port = int(native.get("bind_port", 5062))
    return f'''# Phase 11c: Native TBS connector always talks to local Asterisk.\n[asterisk]\nenabled = true\nregister = true\ncodec = "PCMU"\nbind_addr = "0.0.0.0"\nbind_port = {bind_port}\nremote_host = "127.0.0.1"\nremote_port = 5060\ncontact_host = "{q(native.get('contact_host', '127.0.0.1'))}"\nfrom_domain = "127.0.0.1"\nlocal_user = "{q(native.get('username', 'netcore-tbs-native'))}"\nauth_user = "{q(native.get('username', 'netcore-tbs-native'))}"\npassword = "{q(native.get('password', ''))}"\nrealm = "asterisk"\noptions_interval_secs = 10\ninbound_setup_timeout_secs = 30\n'''


def default_state(cfg: dict[str, Any]) -> dict[str, Any]:
    mode = str(cfg["failover"].get("default_mode", "central"))
    return {
        "schema": "netcore-tbs-sip-failover-state-v1",
        "node_id": cfg["service"]["node_id"],
        "mode": mode,
        "phase": "CENTRAL_ACTIVE" if mode == "central" else "PBX_DIRECT_ACTIVE",
        "central_failures": 0,
        "central_recovery_since": None,
        "last_transition_at": None,
        "last_probe_at": None,
        "last_probe_ok": None,
        "last_reason": "initial",
    }


def read_state(cfg: dict[str, Any]) -> dict[str, Any]:
    path = Path(cfg["failover"]["state_file"])
    if not path.exists():
        return default_state(cfg)
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        if data.get("mode") not in {"central", "pbx_direct"}:
            return default_state(cfg)
        return {**default_state(cfg), **data}
    except Exception:
        return default_state(cfg)


class AsteriskCLI:
    def __init__(self, binary: str):
        self.binary = binary

    def run(self, command: str, check: bool = False) -> subprocess.CompletedProcess[str]:
        proc = subprocess.run([self.binary, "-rx", command], text=True, capture_output=True)
        if check and proc.returncode:
            raise RuntimeError((proc.stderr or proc.stdout or command).strip())
        return proc

    def reload_registrations(self) -> None:
        proc = self.run("module reload res_pjsip_outbound_registration.so")
        if proc.returncode:
            self.run("core reload", check=True)

    def unregister(self, registration_id: str) -> None:
        self.run(f"pjsip send unregister {registration_id}")

    def set_mode_db(self, mode: str) -> None:
        self.run(f"database put netcore failover_mode {mode}", check=True)

    def registration_status(self, registration_id: str) -> str:
        proc = self.run("pjsip show registrations")
        if proc.returncode:
            return "unknown"
        for line in proc.stdout.splitlines():
            if registration_id in line:
                low = line.lower()
                if "registered" in low and "unregistered" not in low:
                    return "registered"
                if "rejected" in low:
                    return "rejected"
                if "unregistered" in low:
                    return "unregistered"
                return line.strip()
        return "absent"

    def aor_available(self, aor_id: str) -> bool:
        proc = self.run(f"pjsip show aor {aor_id}")
        if proc.returncode:
            return False
        text = proc.stdout.lower()
        if re.search(r"\bavail\b", text) and "unavail" not in text:
            return True
        if "status" in text and "available" in text and "unavailable" not in text:
            return True
        return False


class FailoverController:
    def __init__(self, cfg_path: Path, cli: AsteriskCLI | Any, sleeper=time.sleep):
        self.cfg_path = cfg_path
        self.cfg = load(cfg_path)
        ensure(self.cfg)
        self.cli = cli
        self.sleeper = sleeper
        self.n = names(self.cfg)
        self.state = read_state(self.cfg)
        self.stop_requested = False

    @property
    def state_path(self) -> Path:
        return Path(self.cfg["failover"]["state_file"])

    @property
    def active_file(self) -> Path:
        return Path(self.cfg["failover"]["active_registration_file"])

    def save(self) -> None:
        atomic_json(self.state_path, self.state)

    def switch_mode(self, target: str, reason: str, now: float | None = None) -> None:
        if target not in {"central", "pbx_direct"}:
            raise ValueError(target)
        now = time.time() if now is None else now
        current = self.state.get("mode", "central")
        if current == target and self.active_file.exists():
            self.cli.set_mode_db(target)
            return
        if current == "pbx_direct" and target == "central":
            self.state["phase"] = "RECOVERY_PENDING"
            self.save()
            self.cli.unregister(self.n["pbx_reg"])
            self.sleeper(float(self.cfg["failover"].get("unregister_grace_secs", 2)))
        elif current == "central" and target == "pbx_direct":
            self.state["phase"] = "FAILOVER_PENDING"
            self.save()
            self.cli.unregister(self.n["central_reg"])
        atomic_write(self.active_file, render_active_registration(self.cfg, target), 0o640)
        self.cli.reload_registrations()
        self.cli.set_mode_db(target)
        self.state.update({
            "mode": target,
            "phase": "CENTRAL_ACTIVE" if target == "central" else "PBX_DIRECT_ACTIVE",
            "central_failures": 0,
            "central_recovery_since": None,
            "last_transition_at": now,
            "last_reason": reason,
        })
        self.save()

    def central_probe(self) -> tuple[bool, dict[str, Any]]:
        aor_ok = self.cli.aor_available(self.n["central_aor"])
        reg_status = self.cli.registration_status(self.n["central_reg"])
        mode = self.state.get("mode")
        if mode == "central":
            healthy = aor_ok and reg_status == "registered"
        else:
            healthy = aor_ok
        return healthy, {"aor_available": aor_ok, "central_registration": reg_status}

    def tick(self, now: float | None = None) -> dict[str, Any]:
        now = time.time() if now is None else now
        healthy, detail = self.central_probe()
        self.state["last_probe_at"] = now
        self.state["last_probe_ok"] = healthy
        self.state["last_probe"] = detail
        mode = self.state.get("mode", "central")
        fail = self.cfg["failover"]
        threshold = max(1, int(fail.get("failure_threshold", 3)))
        recovery_secs = max(0.0, float(fail.get("recovery_stable_secs", 30)))

        if mode == "central":
            registration_grace = max(0.0, float(fail.get("central_registration_grace_secs", 15)))
            transitioned = self.state.get("last_transition_at")
            in_registration_grace = transitioned is not None and now - float(transitioned) < registration_grace
            if healthy:
                self.state["central_failures"] = 0
                self.state["phase"] = "CENTRAL_ACTIVE"
            elif in_registration_grace:
                self.state["central_failures"] = 0
                self.state["phase"] = "RECOVERY_PENDING"
            else:
                self.state["central_failures"] = int(self.state.get("central_failures", 0)) + 1
                self.state["phase"] = "FAILOVER_PENDING"
                if self.state["central_failures"] >= threshold:
                    self.switch_mode("pbx_direct", "central_unreachable_confirmed", now)
        else:
            if healthy:
                since = self.state.get("central_recovery_since")
                if since is None:
                    self.state["central_recovery_since"] = now
                    self.state["phase"] = "RECOVERY_PENDING"
                elif now - float(since) >= recovery_secs:
                    self.switch_mode("central", "central_stable_recovered", now)
            else:
                self.state["central_recovery_since"] = None
                self.state["phase"] = "PBX_DIRECT_ACTIVE"
        self.save()
        return dict(self.state)

    def run(self) -> None:
        fail = self.cfg["failover"]
        interval = max(1.0, float(fail.get("check_interval_secs", 2)))
        grace = max(0.0, float(fail.get("startup_grace_secs", 10)))
        self.cli.set_mode_db(str(self.state.get("mode", "central")))
        if grace:
            self.sleeper(grace)
        while not self.stop_requested:
            try:
                state = self.tick()
                print(json.dumps({"mode": state["mode"], "phase": state["phase"], "probe": state.get("last_probe")}), flush=True)
            except Exception as exc:
                print(f"failover tick error: {exc}", file=sys.stderr, flush=True)
            self.sleeper(interval)


def render(cfg_path: Path) -> dict[str, Any]:
    cfg = load(cfg_path)
    ensure(cfg)
    out = Path(cfg["asterisk"].get("config_dir", "/etc/asterisk"))
    fail = cfg["failover"]
    state = read_state(cfg)
    files = {
        out / "netcore-tbs-fallback-pjsip.conf": render_pjsip_base(cfg),
        out / "netcore-tbs-fallback-extensions.conf": render_extensions(cfg),
        out / "netcore-tbs-fallback-rtp.conf": render_rtp(cfg),
        Path(fail["central_registration_file"]): render_central_registration(cfg),
        Path(fail["pbx_registration_file"]): render_pbx_registration(cfg),
        Path(fail["active_registration_file"]): render_active_registration(cfg, str(state["mode"])),
        Path(cfg["asterisk"].get("native_snippet_file", "/etc/netcore/tbs-asterisk-local-snippet.toml")): render_native_snippet(cfg),
    }
    for path, content in files.items():
        atomic_write(path, content, 0o640 if path.suffix in {".conf", ".toml"} else None)
    return {"rendered": [str(path) for path in files], "node_id": cfg["service"]["node_id"], "active_mode": state["mode"]}


def status(cfg_path: Path) -> dict[str, Any]:
    cfg = load(cfg_path)
    ensure(cfg)
    cli = AsteriskCLI(str(cfg["asterisk"].get("binary", "/usr/sbin/asterisk")))
    n = names(cfg)
    state = read_state(cfg)
    active_path = Path(cfg["failover"]["active_registration_file"])
    commands = {
        "version": "core show version",
        "registrations": "pjsip show registrations",
        "contacts": "pjsip show contacts",
        "channels": "core show channels concise",
        "astdb_mode": "database get netcore failover_mode",
    }
    result: dict[str, Any] = {
        "node_id": cfg["service"]["node_id"],
        "state": state,
        "central_aor_available": cli.aor_available(n["central_aor"]),
        "central_registration": cli.registration_status(n["central_reg"]),
        "pbx_direct_registration": cli.registration_status(n["pbx_reg"]),
        "active_registration_include": active_path.read_text(encoding="utf-8").strip() if active_path.exists() else None,
        "asterisk": {},
    }
    for key, command in commands.items():
        proc = cli.run(command)
        result["asterisk"][key] = {"ok": proc.returncode == 0, "output": (proc.stdout or proc.stderr).strip()}
    return result


def acquire_lock(path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    handle = path.open("w")
    try:
        fcntl.flock(handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError as exc:
        handle.close()
        raise RuntimeError("another failover controller is already running") from exc
    handle.write(str(os.getpid()))
    handle.flush()
    return handle


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="/etc/netcore/tbs-sip-fallback.toml")
    parser.add_argument("--render", action="store_true")
    parser.add_argument("--status", action="store_true")
    parser.add_argument("--watch", action="store_true")
    parser.add_argument("--once", action="store_true")
    parser.add_argument("--force-mode", choices=["central", "pbx_direct"])
    args = parser.parse_args()
    path = Path(args.config)
    try:
        if args.render:
            print(json.dumps(render(path), indent=2))
            return 0
        if args.status:
            print(json.dumps(status(path), indent=2))
            return 0
        cfg = load(path)
        ensure(cfg)
        cli = AsteriskCLI(str(cfg["asterisk"].get("binary", "/usr/sbin/asterisk")))
        controller = FailoverController(path, cli)
        if args.force_mode:
            controller.switch_mode(args.force_mode, "manual_force")
            print(json.dumps(controller.state, indent=2))
            return 0
        if args.once:
            print(json.dumps(controller.tick(), indent=2))
            return 0
        if args.watch:
            lock = acquire_lock(Path(cfg["failover"]["lock_file"]))
            def stop(_signum, _frame):
                controller.stop_requested = True
            signal.signal(signal.SIGTERM, stop)
            signal.signal(signal.SIGINT, stop)
            try:
                controller.run()
            finally:
                lock.close()
            return 0
        parser.error("choose --render, --status, --watch, --once or --force-mode")
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
