#!/usr/bin/env python3
"""Resolve Observability via the VM; keep rsyslog's last working target offline."""
import argparse
import ipaddress
import json
import os
from pathlib import Path
import subprocess
import tempfile
import urllib.parse
import urllib.request


def endpoint_host(url, networks):
    u = urllib.parse.urlsplit(url)
    if u.scheme != "http" or u.username or u.password or u.path not in ("", "/") or u.query or u.fragment or not u.port:
        raise ValueError("Invalid discovery endpoint")
    ip = ipaddress.ip_address(u.hostname)
    if ip.version != 4 or ip.is_loopback or not any(ip in ipaddress.ip_network(n) for n in networks):
        raise ValueError("Endpoint outside management network")
    return str(ip)


def resolve(cfg, data):
    if any(data.get(k) != v for k, v in {"protocol": "netcore.discovery.v1", "role": "controller",
            "security_mode": "open_lab", "environment": "netcore-openlab"}.items()):
        raise ValueError("Unexpected deployment controller")
    if "observability" in data.get("conflicts", {}):
        raise ValueError("Multiple Observability instances discovered; keeping cached target")
    return endpoint_host(data["endpoints"]["observability"]["url"], cfg["allowed_networks"])


def render(host):
    host = str(ipaddress.IPv4Address(host))
    return f'''# Generated by NetCore log_client.py; edit /etc/netcore/log-client.json.
global(workDirectory="/var/lib/netcore-log-client" maxMessageSize="32k")
module(load="imjournal" StateFile="journal.state" PersistStateInterval="1"
  IgnorePreviousMessages="on" Ratelimit.Interval="0")
module(load="omrelp")
main_queue(queue.type="LinkedList" queue.size="1000")
action(type="omrelp" target="{host}" port="20514" template="RSYSLOG_SyslogProtocol23Format"
  action.resumeRetryCount="-1" action.resumeInterval="5"
  queue.type="Disk" queue.filename="forward" queue.maxDiskSpace="64m"
  queue.maxFileSize="4m" queue.checkpointInterval="1" queue.syncQueueFiles="on"
  queue.saveOnShutdown="on" queue.timeoutEnqueue="0")
'''


class NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, *args, **kwargs):
        raise ValueError("Discovery redirect refused")


def update(cfg, fetch, validate, restart):
    target = Path(cfg["rsyslog_config"])
    try:
        endpoint_host(cfg["controller_url"], cfg["allowed_networks"])
        host = resolve(cfg, fetch(cfg["controller_url"].rstrip("/") + "/api/v1/status"))
    except Exception as exc:
        if target.exists():
            print(f"Discovery unavailable; keeping existing log target: {exc}")
            return False
        host = endpoint_host(f'http://{cfg["fallback_host"]}:8210', cfg["allowed_networks"])
        print(f"Using initial Observability address {host}: {exc}")
    text = render(host)
    if target.exists() and target.read_text() == text:
        return False
    fd, temporary = tempfile.mkstemp(prefix=".log-client-", dir=target.parent)
    try:
        with os.fdopen(fd, "w") as out:
            out.write(text)
            out.flush()
            os.fsync(out.fileno())
        validate(temporary)
        os.replace(temporary, target)
        directory = os.open(target.parent, os.O_RDONLY | os.O_DIRECTORY)
        try:
            os.fsync(directory)
        finally:
            os.close(directory)
        restart()
        return True
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def fetch(url):
    opener = urllib.request.build_opener(urllib.request.ProxyHandler({}), NoRedirect())
    with opener.open(url, timeout=3) as response:
        if response.status != 200:
            raise ValueError(f"Discovery HTTP {response.status}")
        raw = response.read(1024 * 1024 + 1)
        if len(raw) > 1024 * 1024:
            raise ValueError("Discovery response too large")
        return json.loads(raw)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default="/etc/netcore/log-client.json")
    args = parser.parse_args()
    cfg = json.loads(Path(args.config).read_text())
    update(cfg, fetch,
           lambda path: subprocess.run(["rsyslogd", "-N1", "-f", path], check=True, timeout=15),
           lambda: subprocess.run(["systemctl", "try-restart", "netcore-log-client.service"], check=True, timeout=30))


if __name__ == "__main__":
    main()
