#!/usr/bin/env python3
# NETCORE-KOMMENTAR – Was: Enthält die Logik oder Einstellungen für protocol inventory.
# NETCORE-KOMMENTAR – Warum: Die Trennung in eine eigene Datei macht Zuständigkeit, Wartung und Fehlersuche übersichtlicher.

"""Generate the NetCore-Tetra protocol implementation inventory.

The audit is intentionally dependency-free so it can run on development PCs,
Raspberry Pi build hosts and GitHub Actions.  It performs a conservative static
analysis of the Rust source tree.  A green entry means that the relevant codec
entry point exists and contains no obvious runtime placeholder; it is not a
claim of ETSI certification or on-air interoperability.
"""

from __future__ import annotations

import argparse
import csv
import dataclasses
import hashlib
import io
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Iterable, Iterator, Sequence

GENERATED_HEADER = "<!-- Generated by tools/protocol_inventory.py; do not edit manually. -->\n"


# Was: Bündelt Daten und Verhalten für Protokollnachricht (PDU) Datensatz.
# Warum: Zusammengehöriger Zustand und seine Operationen bleiben dadurch an einer klaren Stelle.
@dataclasses.dataclass(frozen=True)
class PduRecord:
    layer: str
    name: str
    direction: str
    path: str
    parser: str
    encoder: str
    runtime: str
    tests: str
    golden_vector: str
    runtime_references: int
    test_references: int
    blockers: tuple[str, ...]
    relevance: str
    phase: str


# Was: Bündelt Daten und Verhalten für sap Datensatz.
# Warum: Zusammengehöriger Zustand und seine Operationen bleiben dadurch an einer klaren Stelle.
@dataclasses.dataclass(frozen=True)
class SapRecord:
    sap: str
    primitive: str
    path: str
    sapmsg_variant: str
    constructed: int
    handled: int
    tests: int
    status: str


# Was: Bündelt Daten und Verhalten für gap Datensatz.
# Warum: Zusammengehöriger Zustand und seine Operationen bleiben dadurch an einer klaren Stelle.
@dataclasses.dataclass(frozen=True)
class GapRecord:
    category: str
    severity: str
    scope: str
    path: str
    line: int
    text: str


# Was: Bündelt Daten und Verhalten für Zustand Datensatz.
# Warum: Zusammengehöriger Zustand und seine Operationen bleiben dadurch an einer klaren Stelle.
@dataclasses.dataclass(frozen=True)
class StateRecord:
    layer: str
    name: str
    path: str
    variants: int
    test_references: int


# Was: Führt den Arbeitsschritt `repo_root` für repo root aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


# Was: Führt den Arbeitsschritt `rel` für rel aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def rel(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


# Was: Diese Funktion liest den vorgesehenen Arbeitsschritt.
# Warum: Der Datenzugriff wird dadurch einheitlich behandelt und Fehler können zentral gemeldet werden.
def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


# Was: Führt den Arbeitsschritt `rust_files` für rust files aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def rust_files(root: Path, *parts: str) -> list[Path]:
    base = root.joinpath(*parts)
    return sorted(p for p in base.rglob("*.rs") if "target" not in p.parts)


# Was: Führt den Arbeitsschritt `extract_function` für extract function aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def extract_function(text: str, name: str) -> str | None:
    """Return a Rust function including its body using lightweight brace matching."""
    match = re.search(rf"\bfn\s+{re.escape(name)}\s*[^{{;]*\{{", text, re.S)
    if not match:
        return None
    start = match.start()
    brace = text.find("{", match.start(), match.end())
    if brace < 0:
        return None
    depth = 0
    in_string = False
    escaped = False
    # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
    # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
    for idx in range(brace, len(text)):
        ch = text[idx]
        if in_string:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == '"':
                in_string = False
            continue
        if ch == '"':
            in_string = True
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return text[start : idx + 1]
    return text[start:]


# Was: Führt den Arbeitsschritt `blockers_in` für blockers in aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def blockers_in(text: str | None) -> tuple[str, ...]:
    if text is None:
        return ()
    patterns = {
        "unimplemented!": r"\bunimplemented!\s*\(",
        "todo!": r"\btodo!\s*\(",
        "panic!": r"\bpanic!\s*\(",
        "unreachable!": r"\bunreachable!\s*\(",
        "TODO": r"\bTODO\b",
        "FIXME": r"\bFIXME\b",
    }
    return tuple(name for name, pat in patterns.items() if re.search(pat, text))


# Was: Führt den Arbeitsschritt `codec_status` für codec Status aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def codec_status(function: str | None) -> str:
    if function is None:
        return "fehlt"
    blockers = blockers_in(function)
    if any(b in blockers for b in ("unimplemented!", "todo!", "panic!", "unreachable!")):
        return "teilweise"
    if "TODO" in blockers or "FIXME" in blockers:
        return "teilweise"
    return "vorhanden"


# Was: Führt den Arbeitsschritt `direction_for` für direction for aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def direction_for(filename: str) -> str:
    stem = Path(filename).stem
    if stem.startswith("d_"):
        return "Downlink"
    if stem.startswith("u_"):
        return "Uplink"
    if stem.startswith("bl_"):
        return "bidirektional"
    if stem.startswith("mac_") or stem.startswith("access_"):
        return "MAC/abhängig"
    return "nicht klassifiziert"


# Was: Führt den Arbeitsschritt `phase_for` für phase for aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def phase_for(layer: str, name: str, path: str) -> str:
    lower = f"{name} {path}".lower()
    if "restore" in lower and layer == "CMCE":
        return "Phase 5 – CMCE Restore"
    if layer == "MLE":
        return "Phase 3 – MLE/Zellwechsel"
    if layer == "MM":
        return "Phase 4 – Mobility Management"
    if layer == "CMCE":
        return "Phase 5/13 – Call Control/SS"
    if layer in {"LLC", "UMAC"}:
        return "Phase 0 – Protokollfundament"
    return "späteres Profil"


# Was: Führt den Arbeitsschritt `relevance_for` für relevance for aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def relevance_for(layer: str, name: str) -> str:
    if layer in {"UMAC", "LLC"}:
        return "Single-Site, Funkzugang"
    if layer == "MLE":
        return "Multi-Site, Zellwechsel"
    if layer == "MM":
        return "Single-/Multi-Site, Mobility"
    if layer == "CMCE":
        if "Sds" in name or "Status" in name:
            return "SDS/Status"
        return "Calls, Single-/Multi-Site"
    return "allgemein"


# Was: Führt den Arbeitsschritt `source_corpus` für source corpus aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def source_corpus(files: Sequence[Path]) -> dict[Path, str]:
    return {p: read(p) for p in files}


# Was: Führt den Arbeitsschritt `count_word` für count word aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def count_word(corpus: dict[Path, str], word: str, excluded: set[Path] | None = None) -> int:
    excluded = excluded or set()
    pat = re.compile(rf"\b{re.escape(word)}\b")
    return sum(len(pat.findall(text)) for path, text in corpus.items() if path not in excluded)


# Was: Führt den Arbeitsschritt `pdu_records` für Protokollnachricht (PDU) records aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def pdu_records(root: Path, all_corpus: dict[Path, str], test_corpus: dict[Path, str]) -> list[PduRecord]:
    records: list[PduRecord] = []
    pdu_root = root / "crates" / "tetra-pdus" / "src"
    # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
    # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
    for path in sorted(pdu_root.glob("*/pdus/*.rs")):
        if path.name == "mod.rs":
            continue
        text = read(path)
        structs = re.findall(r"\bpub\s+struct\s+([A-Za-z0-9_]+)", text)
        if not structs:
            continue
        name = structs[0]
        layer = path.relative_to(pdu_root).parts[0].upper()
        parser_fn = extract_function(text, "from_bitbuf")
        encoder_fn = extract_function(text, "to_bitbuf")
        parser = codec_status(parser_fn)
        encoder = codec_status(encoder_fn)
        file_blockers = tuple(sorted(set(blockers_in(text))))
        runtime = "blockiert" if any(x in file_blockers for x in ("unimplemented!", "todo!", "panic!", "unreachable!")) else (
            "offene Hinweise" if any(x in file_blockers for x in ("TODO", "FIXME")) else "ohne offensichtlichen Blocker"
        )
        runtime_refs = count_word(all_corpus, name, {path})
        test_refs = count_word(test_corpus, name)
        tests = "vorhanden" if test_refs else "fehlt"
        golden = "vorhanden" if any(
            name in text and re.search(r"bitstr|golden|expected|hex|roundtrip", text, re.I)
            for text in test_corpus.values()
        ) else "nicht nachgewiesen"
        path_rel = rel(path, root)
        records.append(
            PduRecord(
                layer=layer,
                name=name,
                direction=direction_for(path.name),
                path=path_rel,
                parser=parser,
                encoder=encoder,
                runtime=runtime,
                tests=tests,
                golden_vector=golden,
                runtime_references=runtime_refs,
                test_references=test_refs,
                blockers=file_blockers,
                relevance=relevance_for(layer, name),
                phase=phase_for(layer, name, path_rel),
            )
        )
    return records


# Was: Diese Funktion liest und prüft sapmsg variants.
# Warum: Ungültige oder unvollständige Eingaben werden dadurch erkannt, bevor sie den Systemzustand beeinflussen.
def parse_sapmsg_variants(text: str) -> set[str]:
    match = re.search(r"pub\s+enum\s+SapMsgInner\s*\{(.*?)\n\}", text, re.S)
    if not match:
        return set()
    body = match.group(1)
    variants: set[str] = set()
    # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
    # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("//") or stripped.startswith("///"):
            continue
        m = re.match(r"([A-Z][A-Za-z0-9_]*)\s*(?:\(|\{|,)", stripped)
        if m:
            variants.add(m.group(1))
    return variants


# Was: Führt den Arbeitsschritt `count_variant_usage` für count variant usage aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def count_variant_usage(files: Sequence[Path], variant: str) -> tuple[int, int]:
    constructed = 0
    handled = 0
    pat = re.compile(rf"SapMsgInner::{re.escape(variant)}\b")
    # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
    # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
    for path in files:
        text = read(path)
        # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
        # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
        for line in text.splitlines():
            if not pat.search(line):
                continue
            if re.search(rf"msg\s*:\s*SapMsgInner::{re.escape(variant)}\b", line):
                constructed += 1
            else:
                handled += 1
    return constructed, handled


# Was: Führt den Arbeitsschritt `sap_records` für sap records aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def sap_records(root: Path) -> list[SapRecord]:
    sap_root = root / "crates" / "tetra-saps" / "src"
    sap_files = sorted(
        p for p in sap_root.rglob("*.rs")
        if p.name not in {"lib.rs", "sapmsg.rs"}
        and "enums" not in p.parts
        and "fields" not in p.parts
    )
    entity_files = rust_files(root, "crates", "tetra-entities", "src") + rust_files(root, "bins")
    test_files = [p for p in root.rglob("*.rs") if "tests" in p.parts]
    variants = parse_sapmsg_variants(read(sap_root / "sapmsg.rs"))
    records: list[SapRecord] = []
    # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
    # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
    for path in sap_files:
        text = read(path)
        names = re.findall(r"\bpub\s+(?:struct|enum)\s+([A-Z][A-Za-z0-9_]*)", text)
        # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
        # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
        for name in names:
            if not re.search(r"(?:Req|Ind|Conf|Confirm|Resp|Demand|Response|Update|Data)$", name):
                continue
            constructed, handled = count_variant_usage(entity_files, name)
            tests = sum(read(p).count(name) for p in test_files)
            if name not in variants:
                status = "nicht in SapMsgInner verdrahtet"
                variant = "nein"
            elif constructed == 0 and handled == 0:
                status = "Variante vorhanden, Runtime-Pfad fehlt"
                variant = "ja"
            elif constructed == 0:
                status = "nur Empfang/Handler sichtbar"
                variant = "ja"
            elif handled == 0:
                status = "nur Erzeugung sichtbar"
                variant = "ja"
            else:
                status = "bidirektional sichtbar"
                variant = "ja"
            records.append(
                SapRecord(
                    sap=path.relative_to(sap_root).parts[0].upper(),
                    primitive=name,
                    path=rel(path, root),
                    sapmsg_variant=variant,
                    constructed=constructed,
                    handled=handled,
                    tests=tests,
                    status=status,
                )
            )
    return sorted(records, key=lambda r: (r.sap, r.primitive))


GAP_PATTERNS = (
    ("unimplemented!", "kritisch", re.compile(r"\bunimplemented!\s*\(")),
    ("todo!", "kritisch", re.compile(r"\btodo!\s*\(")),
    ("panic!", "prüfen", re.compile(r"\bpanic!\s*\(")),
    ("unreachable!", "prüfen", re.compile(r"\bunreachable!\s*\(")),
    ("unimplemented_log!", "offener Runtime-Pfad", re.compile(r"\bunimplemented_log!\s*\(")),
    ("Todo-Typ", "Typ-Platzhalter", re.compile(r"\bTodo\b")),
    ("TODO/FIXME", "technische Schuld", re.compile(r"\b(?:TODO|FIXME)\b")),
)


# Was: Führt den Arbeitsschritt `gap_records` für gap records aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def gap_records(root: Path) -> list[GapRecord]:
    records: list[GapRecord] = []
    # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
    # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
    for path in rust_files(root, "crates") + rust_files(root, "bins") + rust_files(root, "system-backend"):
        scope = "Test" if "tests" in path.parts or path.name.endswith("_test.rs") else "Runtime"
        # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
        # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
        for line_no, line in enumerate(read(path).splitlines(), start=1):
            stripped = line.strip()
            # Runtime macros in comments are historical notes, not executable paths.
            # TODO/FIXME and explicit Todo type placeholders remain part of the inventory.
            if stripped.startswith("//") or stripped.startswith("///"):
                active_patterns = tuple(item for item in GAP_PATTERNS if item[0] in {"TODO/FIXME", "Todo-Typ"})
            else:
                active_patterns = GAP_PATTERNS
            # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
            # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
            for category, severity, pattern in active_patterns:
                if pattern.search(line):
                    effective_severity = severity
                    if scope == "Test" and category in {"panic!", "unreachable!"}:
                        effective_severity = "Test-Assertion"
                    records.append(
                        GapRecord(
                            category=category,
                            severity=effective_severity,
                            scope=scope,
                            path=rel(path, root),
                            line=line_no,
                            text=stripped[:240],
                        )
                    )
    return records


# Was: Führt den Arbeitsschritt `enum_body` für enum body aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def enum_body(text: str, name: str) -> str | None:
    match = re.search(rf"\benum\s+{re.escape(name)}\s*\{{", text)
    if not match:
        return None
    brace = text.find("{", match.start(), match.end())
    depth = 0
    # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
    # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
    for idx in range(brace, len(text)):
        if text[idx] == "{":
            depth += 1
        elif text[idx] == "}":
            depth -= 1
            if depth == 0:
                return text[brace + 1 : idx]
    return None


# Was: Führt den Arbeitsschritt `state_records` für Zustand records aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def state_records(root: Path) -> list[StateRecord]:
    entity_root = root / "crates" / "tetra-entities" / "src"
    sap_root = root / "crates" / "tetra-saps" / "src"
    files = rust_files(root, "crates", "tetra-entities", "src") + rust_files(root, "crates", "tetra-saps", "src")
    tests = {p: read(p) for p in root.rglob("*.rs") if "tests" in p.parts}
    result: list[StateRecord] = []
    # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
    # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
    for path in files:
        text = read(path)
        # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
        # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
        for name in re.findall(r"\b(?:pub\s+)?enum\s+([A-Za-z0-9_]*State[A-Za-z0-9_]*)\s*\{", text):
            body = enum_body(text, name) or ""
            variants = 0
            # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
            # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
            for line in body.splitlines():
                stripped = re.sub(r"//.*$", "", line).strip()
                if re.match(r"^[A-Z][A-Za-z0-9_]*(?:\s*\([^)]*\)|\s*\{[^}]*\})?\s*,?", stripped):
                    variants += 1
            if path.is_relative_to(entity_root):
                parts = path.relative_to(entity_root).parts
                layer = parts[0].upper() if parts else "UNKNOWN"
            else:
                parts = path.relative_to(sap_root).parts
                layer = "SAP/" + (parts[0].upper() if parts else "COMMON")
            test_refs = sum(t.count(name) for t in tests.values())
            result.append(StateRecord(layer, name, rel(path, root), variants, test_refs))
    return sorted(result, key=lambda r: (r.layer, r.name, r.path))


# Was: Führt den Arbeitsschritt `md` für md aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def md(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


# Was: Führt den Arbeitsschritt `table` für table aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def table(headers: Sequence[str], rows: Iterable[Sequence[object]]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    lines.extend("| " + " | ".join(md(v) for v in row) + " |" for row in rows)
    return "\n".join(lines) + "\n"


# Was: Diese Funktion erzeugt conformance.
# Warum: Darstellung und Fachdaten bleiben dadurch voneinander getrennt.
def render_conformance(records: list[PduRecord]) -> str:
    counts = Counter((r.parser, r.encoder) for r in records)
    layers = Counter(r.layer for r in records)
    lines = [
        GENERATED_HEADER.rstrip(),
        "# ETSI-/PDU-Konformitätsmatrix",
        "",
        "> Statische Bestandsaufnahme des aktuellen Quellcodes. `vorhanden` bedeutet, dass der Codec-Einstiegspunkt existiert und keinen offensichtlichen Runtime-Platzhalter enthält. Dies ist **keine ETSI-Zertifizierung** und ersetzt weder Golden Vectors noch On-Air-Tests.",
        "",
        "## Übersicht",
        "",
        f"- erfasste PDU-Implementierungen: **{len(records)}**",
        f"- Schichten: " + ", ".join(f"{k} {v}" for k, v in sorted(layers.items())),
        f"- Parser und Encoder beide ohne offensichtlichen Blocker: **{sum(1 for r in records if r.parser == 'vorhanden' and r.encoder == 'vorhanden')}**",
        f"- mindestens ein Codec-Pfad teilweise oder fehlend: **{sum(1 for r in records if r.parser != 'vorhanden' or r.encoder != 'vorhanden')}**",
        f"- PDU-Dateien ohne nachgewiesenen Testverweis: **{sum(1 for r in records if r.tests == 'fehlt')}**",
        "",
        "## Bewertungslegende",
        "",
        table(
            ["Status", "Bedeutung"],
            [
                ("vorhanden", "Methode vorhanden, kein offensichtlicher `unimplemented!`, `todo!`, `panic!`, TODO oder FIXME im Methodenkörper"),
                ("teilweise", "Methode vorhanden, aber mit Runtime-Platzhalter oder offenem TODO/FIXME"),
                ("fehlt", "kein passender Codec-Einstiegspunkt im Modul"),
                ("nicht nachgewiesen", "statisch kein Golden-Vector-Test erkennbar"),
            ],
        ).rstrip(),
        "",
    ]
    # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
    # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
    for layer in sorted(layers):
        subset = [r for r in records if r.layer == layer]
        lines += [
            f"## {layer}",
            "",
            table(
                ["PDU", "Richtung", "Parser", "Encoder", "Runtime", "Tests", "Golden Vector", "Phase", "Datei"],
                [
                    (
                        r.name,
                        r.direction,
                        r.parser,
                        r.encoder,
                        r.runtime,
                        r.tests,
                        r.golden_vector,
                        r.phase,
                        f"`{r.path}`",
                    )
                    for r in subset
                ],
            ).rstrip(),
            "",
        ]
    return "\n".join(lines).rstrip() + "\n"


# Was: Diese Funktion erzeugt saps.
# Warum: Darstellung und Fachdaten bleiben dadurch voneinander getrennt.
def render_saps(records: list[SapRecord]) -> str:
    by_sap = Counter(r.sap for r in records)
    lines = [
        GENERATED_HEADER.rstrip(),
        "# SAP-Primitive- und Routing-Matrix",
        "",
        "> Die Matrix zeigt die statisch erkennbare Verdrahtung über `SapMsgInner`. `constructed` und `handled` sind konservative Quelltexttreffer und dienen als Arbeitsliste, nicht als Laufzeitbeweis.",
        "",
        "## Übersicht",
        "",
        f"- erfasste Primitive: **{len(records)}**",
        f"- nicht in `SapMsgInner` verdrahtet: **{sum(1 for r in records if r.sapmsg_variant == 'nein')}**",
        f"- vorhandene Variante ohne sichtbaren Runtime-Pfad: **{sum(1 for r in records if 'Runtime-Pfad fehlt' in r.status)}**",
        f"- Primitive ohne Testverweis: **{sum(1 for r in records if r.tests == 0)}**",
        "",
    ]
    # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
    # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
    for sap in sorted(by_sap):
        subset = [r for r in records if r.sap == sap]
        lines += [
            f"## {sap}",
            "",
            table(
                ["Primitive", "SapMsgInner", "erzeugt", "behandelt", "Testtreffer", "Status", "Definition"],
                [(r.primitive, r.sapmsg_variant, r.constructed, r.handled, r.tests, r.status, f"`{r.path}`") for r in subset],
            ).rstrip(),
            "",
        ]
    return "\n".join(lines).rstrip() + "\n"


# Was: Diese Funktion erzeugt gaps.
# Warum: Darstellung und Fachdaten bleiben dadurch voneinander getrennt.
def render_gaps(gaps: list[GapRecord], saps: list[SapRecord], pdus: list[PduRecord]) -> str:
    by_category = Counter(g.category for g in gaps)
    lines = [
        GENERATED_HEADER.rstrip(),
        "# Implementierungslücken und Runtime-Risiken",
        "",
        "## Zusammenfassung",
        "",
        table(["Kategorie", "Treffer"], sorted(by_category.items())).rstrip(),
        "",
        "## Priorität für SWMI Foundation 1",
        "",
        "1. aktive `unimplemented!`-/`todo!`-Pfade in TLMC, TLPD, MLE und den zugehörigen PDU-Codecs entfernen;",
        "2. nicht in `SapMsgInner` verdrahtete TLMC-/TLPD-Primitive typisieren und routen;",
        "3. PDU-Parser mit Runtime-Panics vor Fuzzing und On-Air-Eingaben schützen;",
        "4. für alle bereits produktiv verwendeten PDUs Golden Vectors ergänzen;",
        "5. verbleibende `unimplemented_log!`-Pfade nach Schicht und Roadmap-Phase abarbeiten.",
        "",
        "## Nicht erreichbare oder unvollständige SAP-Pfade",
        "",
        table(
            ["SAP", "Primitive", "Status", "Definition"],
            [
                (r.sap, r.primitive, r.status, f"`{r.path}`")
                for r in saps
                if r.sapmsg_variant == "nein" or "Runtime-Pfad fehlt" in r.status or r.constructed == 0 or r.handled == 0
            ],
        ).rstrip(),
        "",
        "## PDU-Codecs mit fehlendem oder teilweisem Parser/Encoder",
        "",
        table(
            ["Schicht", "PDU", "Parser", "Encoder", "Blocker", "Datei"],
            [
                (r.layer, r.name, r.parser, r.encoder, ", ".join(r.blockers) or "—", f"`{r.path}`")
                for r in pdus
                if r.parser != "vorhanden" or r.encoder != "vorhanden"
            ],
        ).rstrip(),
        "",
        "## Aktive und dokumentierte Quelltexttreffer",
        "",
        table(
            ["Kategorie", "Schwere", "Bereich", "Datei", "Zeile", "Ausschnitt"],
            [(g.category, g.severity, g.scope, f"`{g.path}`", g.line, f"`{g.text}`") for g in gaps],
        ).rstrip(),
        "",
    ]
    return "\n".join(lines).rstrip() + "\n"


# Was: Diese Funktion erzeugt states.
# Warum: Darstellung und Fachdaten bleiben dadurch voneinander getrennt.
def render_states(records: list[StateRecord]) -> str:
    required = [
        ("MLE Cell State", "Typfundament mit `MleCellState` vorhanden; Runtime-Transitionen folgen mit den MLE-Zellwechsel-PDUs", "Foundation 2/Phase 3"),
        ("MM Registration State", "teilweise über Client-/Registration-Zustände vorhanden", "Phase 4"),
        ("CMCE Group Call", "vorhandene Call-State-Typen prüfen und formalisieren", "Phase 5"),
        ("CMCE Individual Call", "vorhandene Individual-Call-State-Typen prüfen und formalisieren", "Phase 5"),
        ("SNDCP Context State", "PDP-State vorhanden; vollständige Context-Transitionen folgen", "Phase 11"),
        ("LTPD Link State", "Context Registry, TxReporter-gestützte Transfers, Replay-Schutz und Lifecycle-Runtime vorhanden", "Paket E ✅"),
        ("LLC Link State", "TxReporter bindet LTPD an reale LLC/MAC-Übertragung; vollständige Advanced-Link-State-Machine bleibt offen", "Phase 3"),
        ("Channel Change State", "TLMC Select/Response-Lifecycle vorhanden; MLE-Zellwechseltransitionen fehlen", "Phase 3"),
    ]
    return "\n".join(
        [
            GENERATED_HEADER.rstrip(),
            "# Zustandsmaschinen-Inventur",
            "",
            "> Automatisch gefundene Rust-Enums mit `State` im Namen. Implizite Zustände in Maps, Booleans und Handler-Reihenfolgen werden durch diese Suche nicht vollständig erkannt und bleiben ein manueller Reviewpunkt.",
            "",
            "## Gefundene State-Typen",
            "",
            table(
                ["Schicht", "Typ", "Varianten", "Testtreffer", "Datei"],
                [(r.layer, r.name, r.variants, r.test_references, f"`{r.path}`") for r in records],
            ).rstrip(),
            "",
            "## Für die Roadmap geforderte Zustandsmaschinen",
            "",
            table(["Bereich", "Inventurstatus", "Roadmap"], required).rstrip(),
            "",
            "## Nächster manueller Review",
            "",
            "- Zustände, Timer und Übergänge pro Entity als Diagramm festhalten;",
            "- Transitionen mit auslösendem SAP/PDU und Fehlerpfad verknüpfen;",
            "- persistierbare Zustände von rein lokalen TDMA-/Ressourcenzuständen trennen;",
            "- jede Transition mit mindestens einem Unit- oder Integrationstest versehen.",
            "",
        ]
    )


# Was: Diese Funktion erzeugt summary.
# Warum: Darstellung und Fachdaten bleiben dadurch voneinander getrennt.
def render_summary(pdus: list[PduRecord], saps: list[SapRecord], gaps: list[GapRecord], states: list[StateRecord]) -> str:
    critical = sum(1 for g in gaps if g.severity == "kritisch" and g.scope == "Runtime")
    missing_saps = sum(1 for r in saps if r.sapmsg_variant == "nein")
    partial_pdus = sum(1 for r in pdus if r.parser != "vorhanden" or r.encoder != "vorhanden")
    tlmc = [r for r in saps if r.sap == "TLMC"]
    ltpd = [r for r in saps if r.sap == "LTPD"]
    return "\n".join(
        [
            GENERATED_HEADER.rstrip(),
            "# SWMI Foundation 1 – Protokollinventur",
            "",
            "## Ergebnis",
            "",
            "Paket A stellt die reproduzierbare Inventur bereit. Paket B ergänzt die typisierten TLMC-/TLPD-Primitive und grundlegenden Zustände. Paket C aktiviert die lokale TLMC-Runtime. Paket D ergänzt bidirektionales SNDCP-Routing und den lokalen Link-Lifecycle. Paket E schließt Foundation 1 mit TxReporter-gestützten Transferergebnissen, Duplicate- und Replay-Schutz, Cancel/Timeout-Robustheit, negativen Zustandsübergängen und einem wiederverwendbaren Zwei-Zellen-Testharness ab. Die Matrix bleibt die laufend aktualisierte Bestandsaufnahme für die folgenden MLE- und Multi-Site-Pakete.",
            "",
            table(
                ["Messgröße", "Stand"],
                [
                    ("PDU-Module", len(pdus)),
                    ("PDU-Codecs teilweise/fehlend", partial_pdus),
                    ("SAP-Primitive", len(saps)),
                    ("SAP-Primitive nicht in SapMsgInner", missing_saps),
                    ("TLMC-Primitive inventarisiert", len(tlmc)),
                    ("LTPD-Primitive inventarisiert", len(ltpd)),
                    ("kritische Runtime-Platzhalter", critical),
                    ("gefundene State-Typen", len(states)),
                ],
            ).rstrip(),
            "",
            "## Erzeugte Artefakte",
            "",
            "- `Docs/ETSI_CONFORMANCE_MATRIX.md` – PDU-Parser/Encoder, Testabdeckung und Roadmap-Zuordnung",
            "- `Docs/SAP_PRIMITIVE_MATRIX.md` – SAP-Primitive und statisch sichtbare Routingpfade",
            "- `Docs/IMPLEMENTATION_GAPS.md` – TODO, `unimplemented!`, `unimplemented_log!`, Panic-Pfade und fehlende Verdrahtung",
            "- `Docs/STATE_MACHINE_INVENTORY.md` – vorhandene und geforderte Zustandsmodelle",
            "- `Docs/generated/protocol_inventory.json` – maschinenlesbare Gesamtdaten",
            "- `Docs/generated/pdu_inventory.csv` und `sap_inventory.csv` – Tabellenexport",
            "- `tools/protocol_inventory.py` – deterministischer Generator",
            "- `tools/check_protocol_inventory.sh` – lokaler Konsistenzcheck",
            "- `.github/workflows/protocol-inventory.yml` – CI-Prüfung gegen veraltete Inventurdateien",
            "",
            "## Bedienung",
            "",
            "```bash",
            "python3 tools/protocol_inventory.py",
            "./tools/check_protocol_inventory.sh",
            "```",
            "",
            "## Wichtige Auslegung",
            "",
            "Die Matrix bewertet den Quellcode konservativ. Ein Codec ohne offensichtlichen Platzhalter gilt als statisch vorhanden, aber erst Golden Vectors, Integrationstests und On-Air-Tests machen daraus eine belastbare Implementierung.",
            "",
            "## Nächster Arbeitsschritt",
            "",
            "Paket E schließt SWMI Foundation 1 ab. Als Nächstes folgt die MLE-Zellwechselbasis mit vollständigen Codecs und Zustandsübergängen für D-NEW-CELL, D-PREPARE-FAIL, U/D-RESTORE und D-CHANNEL-RESPONSE.",
            "",
        ]
    )



# Was: Führt den Arbeitsschritt `csv_text` für csv text aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def csv_text(records: Sequence[object]) -> str:
    if not records:
        return ""
    fields = [f.name for f in dataclasses.fields(records[0])]
    handle = io.StringIO(newline="")
    writer = csv.DictWriter(handle, fieldnames=fields, lineterminator="\n")
    writer.writeheader()
    # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
    # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
    for record in records:
        row = dataclasses.asdict(record)
        # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
        # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
        for key, value in row.items():
            if isinstance(value, tuple):
                row[key] = ";".join(value)
        writer.writerow(row)
    return handle.getvalue()

# Was: Diese Funktion schreibt csv.
# Warum: Die Ausgabe wird dadurch einheitlich erzeugt und Schreibfehler können behandelt werden.
def write_csv(path: Path, records: Sequence[object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not records:
        path.write_text("", encoding="utf-8")
        return
    fields = [f.name for f in dataclasses.fields(records[0])]
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, lineterminator="\n")
        writer.writeheader()
        # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
        # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
        for record in records:
            row = dataclasses.asdict(record)
            # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
            # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
            for key, value in row.items():
                if isinstance(value, tuple):
                    row[key] = ";".join(value)
            writer.writerow(row)


# Was: Wandelt den vorhandenen Wert in JSON-Daten data um oder stellt ihn in dieser Form bereit.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def as_json_data(pdus: list[PduRecord], saps: list[SapRecord], gaps: list[GapRecord], states: list[StateRecord]) -> dict[str, object]:
    return {
        "schema_version": 1,
        "note": "Static source inventory; not a claim of ETSI certification.",
        "summary": {
            "pdu_count": len(pdus),
            "sap_primitive_count": len(saps),
            "gap_count": len(gaps),
            "state_type_count": len(states),
        },
        "pdus": [dataclasses.asdict(r) for r in pdus],
        "sap_primitives": [dataclasses.asdict(r) for r in saps],
        "gaps": [dataclasses.asdict(r) for r in gaps],
        "state_types": [dataclasses.asdict(r) for r in states],
    }


# Was: Führt den Arbeitsschritt `outputs` für outputs aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def outputs(root: Path) -> dict[Path, str]:
    production_files = rust_files(root, "crates") + rust_files(root, "bins") + rust_files(root, "system-backend")
    test_files = [p for p in root.rglob("*.rs") if "tests" in p.parts]
    production_corpus = source_corpus(production_files)
    tests_corpus = source_corpus(test_files)
    pdus = pdu_records(root, production_corpus, tests_corpus)
    saps = sap_records(root)
    gaps = gap_records(root)
    states = state_records(root)
    data = as_json_data(pdus, saps, gaps, states)
    return {
        root / "Docs" / "SWMI_FOUNDATION_1_INVENTORY.md": render_summary(pdus, saps, gaps, states),
        root / "Docs" / "ETSI_CONFORMANCE_MATRIX.md": render_conformance(pdus),
        root / "Docs" / "SAP_PRIMITIVE_MATRIX.md": render_saps(saps),
        root / "Docs" / "IMPLEMENTATION_GAPS.md": render_gaps(gaps, saps, pdus),
        root / "Docs" / "STATE_MACHINE_INVENTORY.md": render_states(states),
        root / "Docs" / "generated" / "protocol_inventory.json": json.dumps(data, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
        root / "Docs" / "generated" / "pdu_inventory.csv": csv_text(pdus),
        root / "Docs" / "generated" / "sap_inventory.csv": csv_text(saps),
        root / "Docs" / "generated" / "gap_inventory.csv": csv_text(gaps),
        root / "Docs" / "generated" / "state_inventory.csv": csv_text(states),
    }


# Was: Diese Funktion erzeugt csv files.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def generate_csv_files(root: Path) -> None:
    production_files = rust_files(root, "crates") + rust_files(root, "bins") + rust_files(root, "system-backend")
    tests = [p for p in root.rglob("*.rs") if "tests" in p.parts]
    pdus = pdu_records(root, source_corpus(production_files), source_corpus(tests))
    saps = sap_records(root)
    gaps = gap_records(root)
    states = state_records(root)
    write_csv(root / "Docs" / "generated" / "pdu_inventory.csv", pdus)
    write_csv(root / "Docs" / "generated" / "sap_inventory.csv", saps)
    write_csv(root / "Docs" / "generated" / "gap_inventory.csv", gaps)
    write_csv(root / "Docs" / "generated" / "state_inventory.csv", states)


# Was: Führt den Arbeitsschritt `digest` für digest aus.
# Warum: Der abgegrenzte Arbeitsschritt kann dadurch wiederverwendet, getestet und leichter verstanden werden.
def digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


# Was: Startet das Programm, lädt die benötigten Einstellungen und übergibt an den eigentlichen Dienstablauf.
# Warum: Ein klarer Einstiegspunkt hält Startreihenfolge, Fehlerausgabe und geordnetes Beenden zusammen.
def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when tracked generated files are stale")
    args = parser.parse_args(argv)
    root = repo_root()
    generated = outputs(root)
    stale: list[str] = []
    # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
    # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
    for path, content in generated.items():
        if args.check:
            current = read(path) if path.exists() else ""
            if digest(current) != digest(content):
                stale.append(rel(path, root))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if args.check:
        # CSV consistency is checked by regenerating into memory-unfriendly temp-free comparison.
        # They are deterministic, so normal generation before commit is the canonical workflow.
        if stale:
            print("Protocol inventory is stale:", file=sys.stderr)
            # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
            # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
            for item in stale:
                print(f"  - {item}", file=sys.stderr)
            print("Run: python3 tools/protocol_inventory.py", file=sys.stderr)
            return 1
        print("Protocol inventory is up to date.")
        return 0
    print("Generated protocol inventory:")
    # Was: Wiederholt den folgenden Abschnitt für mehrere Einträge oder solange die Bedingung erfüllt ist.
    # Warum: Gleichartige Daten oder wiederkehrende Prüfungen werden dadurch vollständig und einheitlich abgearbeitet.
    for path in sorted(generated):
        print(f"  - {rel(path, root)}")
    return 0


# Was: Startet den Programmablauf nur dann, wenn diese Datei direkt ausgeführt wird.
# Warum: Beim Import als Modul sollen nur Funktionen bereitstehen und keine Nebenwirkungen automatisch starten.
if __name__ == "__main__":
    raise SystemExit(main())
